export type CourseDetailModal =
    | "updateMaterial"
    | "deleteMaterial"
    | "createMaterial"
    | "deleteQuiz"
    | "createQuiz"
    | "createFeedPost"
    | "deleteFeedPost"
    | "updateFeedPost"
    | "loginRequired"
    | "quizResults"
    | "deleteCourse"
    | "schedulePublication"
    | "createModule"
    | "updateModule"
    | "deleteModule"
    | "materialResults"
    | null;
