// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tda26.Server.Data;

#nullable disable

namespace tda26.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AccountShopItem", b =>
                {
                    b.Property<Guid>("OwnedByAccountsUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ShopItemsUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("OwnedByAccountsUuid", "ShopItemsUuid");

                    b.HasIndex("ShopItemsUuid");

                    b.ToTable("AccountShopItem");
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.Property<Guid>("CoursesUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagsUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("CoursesUuid", "TagsUuid");

                    b.HasIndex("TagsUuid");

                    b.ToTable("CourseTag");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Account", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Ducks")
                        .HasColumnType("int");

                    b.Property<Guid?>("EquippedAvatarUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquippedBadgeUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquippedBannerUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquippedEffectUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquippedTitleUuid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganizationUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Uuid");

                    b.HasIndex("EquippedAvatarUuid");

                    b.HasIndex("EquippedBadgeUuid");

                    b.HasIndex("EquippedBannerUuid");

                    b.HasIndex("EquippedEffectUuid");

                    b.HasIndex("EquippedTitleUuid");

                    b.HasIndex("OrganizationUuid");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasDiscriminator().HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Icon")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Course", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1048)
                        .HasColumnType("varchar(1048)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("LecturerUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("OrganizationUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Uuid");

                    b.HasIndex("CategoryUuid");

                    b.HasIndex("LecturerUuid");

                    b.HasIndex("OrganizationUuid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.CourseModule", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Description")
                        .HasMaxLength(1048)
                        .HasColumnType("varchar(1048)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("CourseUuid");

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.DailyRewardDay", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<DateOnly>("RewardDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("AccountUuid", "RewardDate")
                        .IsUnique();

                    b.ToTable("DailyRewardDays");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.DailyRewardTaskState", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<Guid>("DailyRewardDayUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("DailyRewardDayUuid", "TaskCode")
                        .IsUnique();

                    b.ToTable("DailyRewardTaskStates");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.FeedPost", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AccountUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<bool>("Edited")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("AccountUuid");

                    b.HasIndex("CourseUuid");

                    b.ToTable("FeedPosts");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Material", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Description")
                        .HasMaxLength(1048)
                        .HasColumnType("varchar(1048)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ModuleUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("CourseUuid");

                    b.HasIndex("ModuleUuid");

                    b.ToTable("Materials");

                    b.HasDiscriminator().HasValue("Material");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Organization", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uuid");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Question", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1048)
                        .HasColumnType("varchar(1048)");

                    b.HasKey("Uuid");

                    b.HasIndex("QuizUuid");

                    b.ToTable("Questions");

                    b.HasDiscriminator().HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuestionOption", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Uuid");

                    b.HasIndex("QuestionUuid");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Quiz", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ModuleUuid")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("CourseUuid");

                    b.HasIndex("ModuleUuid");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizAnswer", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuestionUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuizResultUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.HasIndex("QuestionUuid");

                    b.HasIndex("QuizResultUuid");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizAnswerOption", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnswerUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OptionUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.HasIndex("AnswerUuid");

                    b.HasIndex("OptionUuid");

                    b.ToTable("QuizAnswerOptions");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizResult", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("QuizUuid")
                        .HasColumnType("char(36)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimeSeconds")
                        .HasColumnType("int");

                    b.HasKey("Uuid");

                    b.HasIndex("QuizUuid");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Rating", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("CourseUuid");

                    b.HasIndex("AccountUuid", "CourseUuid")
                        .IsUnique();

                    b.ToTable("Ratings");

                    b.HasDiscriminator().HasValue("Rating");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tda26.Server.Data.Models.ShopItem", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("PriceInDucks")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.ToTable("ShopItems");

                    b.HasDiscriminator().HasValue("ShopItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Tag", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("CreatedAt"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTimeOffset>("UpdatedAt"));

                    b.HasKey("Uuid");

                    b.HasIndex("CategoryUuid");

                    b.HasIndex("DisplayName");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Admin", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Account");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Lecturer", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Account");

                    b.Property<string>("Bio")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Bio");

                    b.Property<string>("Claim")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.PrimitiveCollection<string>("Emails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LastName");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("MiddleName");

                    b.PrimitiveCollection<string>("MobileNumbers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PictureUrl")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("PictureUrl");

                    b.Property<ushort>("PricePerHour")
                        .HasColumnType("smallint unsigned");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleAfter")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TitleBefore")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasDiscriminator().HasValue("Lecturer");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Student", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Account");

                    b.Property<string>("Bio")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Bio");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LastName");

                    b.Property<string>("MiddleName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("MiddleName");

                    b.Property<string>("PictureUrl")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("PictureUrl");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.FileMaterial", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Material");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastDownload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.Property<long>("TotalBytesDownloaded")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("FileMaterial");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.UrlMaterial", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Material");

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastClickedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasDiscriminator().HasValue("UrlMaterial");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Question");

                    b.HasDiscriminator().HasValue("MultipleChoiceQuestion");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Question");

                    b.HasDiscriminator().HasValue("SingleChoiceQuestion");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Dislike", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Rating");

                    b.ToTable("Ratings");

                    b.HasDiscriminator().HasValue("Dislike");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Like", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.Rating");

                    b.ToTable("Ratings");

                    b.HasDiscriminator().HasValue("Like");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.AvatarShopItem", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.ShopItem");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext");

                    b.ToTable("ShopItems");

                    b.HasDiscriminator().HasValue("AvatarShopItem");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.BadgeShopItem", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.ShopItem");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext");

                    b.ToTable("ShopItems");

                    b.HasDiscriminator().HasValue("BadgeShopItem");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.BannerShopItem", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.ShopItem");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext");

                    b.ToTable("ShopItems");

                    b.HasDiscriminator().HasValue("BannerShopItem");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.EffectShopItem", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.ShopItem");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext");

                    b.ToTable("ShopItems");

                    b.HasDiscriminator().HasValue("EffectShopItem");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.TitleShopItem", b =>
                {
                    b.HasBaseType("tda26.Server.Data.Models.ShopItem");

                    b.ToTable("ShopItems");

                    b.HasDiscriminator().HasValue("TitleShopItem");
                });

            modelBuilder.Entity("AccountShopItem", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnedByAccountsUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.ShopItem", null)
                        .WithMany()
                        .HasForeignKey("ShopItemsUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Account", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.AvatarShopItem", "EquippedAvatar")
                        .WithMany()
                        .HasForeignKey("EquippedAvatarUuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tda26.Server.Data.Models.BadgeShopItem", "EquippedBadge")
                        .WithMany()
                        .HasForeignKey("EquippedBadgeUuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tda26.Server.Data.Models.BannerShopItem", "EquippedBanner")
                        .WithMany()
                        .HasForeignKey("EquippedBannerUuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tda26.Server.Data.Models.EffectShopItem", "EquippedEffect")
                        .WithMany()
                        .HasForeignKey("EquippedEffectUuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tda26.Server.Data.Models.TitleShopItem", "EquippedTitle")
                        .WithMany()
                        .HasForeignKey("EquippedTitleUuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquippedAvatar");

                    b.Navigation("EquippedBadge");

                    b.Navigation("EquippedBanner");

                    b.Navigation("EquippedEffect");

                    b.Navigation("EquippedTitle");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Account", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationUuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Course", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUuid");

                    b.HasOne("tda26.Server.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("LecturerUuid");

                    b.HasOne("tda26.Server.Data.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.CourseModule", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.DailyRewardDay", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.DailyRewardTaskState", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.DailyRewardDay", "DailyRewardDay")
                        .WithMany("Tasks")
                        .HasForeignKey("DailyRewardDayUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRewardDay");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.FeedPost", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountUuid");

                    b.HasOne("tda26.Server.Data.Models.Course", "Course")
                        .WithMany("Feed")
                        .HasForeignKey("CourseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Material", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.CourseModule", "Module")
                        .WithMany("Materials")
                        .HasForeignKey("ModuleUuid");

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Question", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuestionOption", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Quiz", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Course", "Course")
                        .WithMany("Quizzes")
                        .HasForeignKey("CourseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.CourseModule", "Module")
                        .WithMany("Quizzes")
                        .HasForeignKey("ModuleUuid");

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizAnswer", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.QuizResult", "QuizResult")
                        .WithMany("Answers")
                        .HasForeignKey("QuizResultUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizAnswerOption", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.QuizAnswer", "Answer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("AnswerUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.QuestionOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizResult", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Rating", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Account", "Account")
                        .WithMany("Ratings")
                        .HasForeignKey("AccountUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tda26.Server.Data.Models.Course", "Course")
                        .WithMany("Ratings")
                        .HasForeignKey("CourseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Tag", b =>
                {
                    b.HasOne("tda26.Server.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUuid");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Account", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Course", b =>
                {
                    b.Navigation("Feed");

                    b.Navigation("Materials");

                    b.Navigation("Modules");

                    b.Navigation("Quizzes");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.CourseModule", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.DailyRewardDay", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("tda26.Server.Data.Models.QuizResult", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
