name: Build and push Web App to TdA

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # vytvoreni env souboru pro backend
    env:
      BACKEND_ENV_B64: ${{ secrets.DOTENV_BACKEND_B64 }} # base64 obsahu backend .env

    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4


      - name: Upload to TdA
        uses: Student-Cyber-Games/upload-app@tda-26
        with:
          tdc_token: ${{ secrets.TDC_TOKEN }}